modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/PlanetSand_mod/issues" #optional

[[mods]]
modId="planetsand"
version="${version}"
displayName="Planet Sand Oddities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/planet-sand-mod"
updateJSONURL="https://github.com/MeinKraft/PlanetSand_mod/raw/main/update.json"
authors="ยง4Crimson_Fluff"
logoFile="logo.png" #optional
credits="" #optional
description=''' Complementary mod to the Planet Sand modpack '''

[[dependencies.planetsand]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
  side="BOTH"
[[dependencies.planetsand]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
